name: Terraform Apply

on:
  push:
    workflows: ["Terraform Plan"]  # Trigger after the plan workflow finishes
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
          run: |
            echo "Manual approval required. Please trigger this workflow manually after reviewing the plan output."
            exit 1  # This stops the workflow until you manually re-run it
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::400528359242:role/github-actions-ecs-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false -lock-timeout=60s -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false -lock-timeout=60s tfplan